In [25]:
import numpy as np
points = np.array([
            [1100,410],
            [715,410],
            [200,1010],
            [1430,1010]
        ])
t= 0.4

In [26]:
corr2,corr3 = points[1].copy(),points[2].copy()
corr1,corr4 = points[0].copy(),points[3].copy()

corr5 = corr3 + t*(corr2-corr3)
corr6 = corr4 + t*(corr1-corr4)



In [27]:
points

array([[1100,  410],
       [ 715,  410],
       [ 200, 1010],
       [1430, 1010]])

In [36]:
np.append(points,np.array([corr5,corr6]),axis=0)

array([[1100.,  410.],
       [ 715.,  410.],
       [ 200., 1010.],
       [1430., 1010.],
       [ 406.,  770.],
       [1298.,  770.]])

In [28]:
new_points = np.array([corr5,corr6])
new_points

array([[ 406.,  770.],
       [1298.,  770.]])

In [29]:
all_points = np.append(points,new_points,axis=0)
all_points

array([[1100.,  410.],
       [ 715.,  410.],
       [ 200., 1010.],
       [1430., 1010.],
       [ 406.,  770.],
       [1298.,  770.]])

In [33]:
all_points = np.concatenate(points,corr5,axis=0)
all_points

TypeError: concatenate() got multiple values for argument 'axis'

In [3]:
t= 0.4
corr1 + t*(corr2-corr1)

array([509., 650.])

In [6]:
from datetime import timedelta
import time
startTime = time.time()
time.sleep(2)
end = time.time()
print(str(timedelta(seconds= end - startTime)))

0:00:02.000241


In [7]:
from transformers import AutoModel, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("ucaslcl/GOT-OCR2_0", trust_remote_code=True)
GOT_model = AutoModel.from_pretrained("ucaslcl/GOT-OCR2_0", trust_remote_code=True, device_map='cuda')

/home/hlink/workspace/road_segementation/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
img = 
inputs = tokenizer('data/overspeeding_vehicles_ss/overspeeding_vehicle_1.png',return_tensors='pt', padding=True, truncation=True, max_length=512)

In [9]:
input_ids = inputs['input_ids']
attention_mask = inputs['attention_mask']


In [10]:
output = GOT_model(input_ids=input_ids, attention_mask=attention_mask)

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)