In [25]:
import numpy as np
points = np.array([
            [1100,410],
            [715,410],
            [200,1010],
            [1430,1010]
        ])
t= 0.4

In [26]:
corr2,corr3 = points[1].copy(),points[2].copy()
corr1,corr4 = points[0].copy(),points[3].copy()

corr5 = corr3 + t*(corr2-corr3)
corr6 = corr4 + t*(corr1-corr4)



In [27]:
points

array([[1100,  410],
       [ 715,  410],
       [ 200, 1010],
       [1430, 1010]])

In [36]:
np.append(points,np.array([corr5,corr6]),axis=0)

array([[1100.,  410.],
       [ 715.,  410.],
       [ 200., 1010.],
       [1430., 1010.],
       [ 406.,  770.],
       [1298.,  770.]])

In [28]:
new_points = np.array([corr5,corr6])
new_points

array([[ 406.,  770.],
       [1298.,  770.]])

In [29]:
all_points = np.append(points,new_points,axis=0)
all_points

array([[1100.,  410.],
       [ 715.,  410.],
       [ 200., 1010.],
       [1430., 1010.],
       [ 406.,  770.],
       [1298.,  770.]])

In [33]:
all_points = np.concatenate(points,corr5,axis=0)
all_points

TypeError: concatenate() got multiple values for argument 'axis'

In [3]:
t= 0.4
corr1 + t*(corr2-corr1)

array([509., 650.])